### ISSUE TITLE
Installation failed!

### ISSUE THREAD

**Issue by pixy61** [kieranjmartin/viewenhance#1]
install_github("martik32/viewenhance")
Downloading GitHub repo martik32/viewenhance@master
from URL https://api.github.com/repos/martik32/viewenhance/zipball/master
Installation failed: Not Found (404)

**Comment by kieranjmartin** [comment]
Apologies @pixy61, the read me is out of date (this repo was originally built on a private github). You need to use install_github("kieranjmartin/viewenhance"). I will update the readme accordingly!

**Comment by pixy61** [comment]
Still not working
Error : invalid DESCRIPTION file
Malformed maintainer field.
See section 'The DESCRIPTION file' in the 'Writing R Extensions'
manual.
ERROR: installing package DESCRIPTION failed for package 'viewenhance'

**Comment by kieranjmartin** [comment]
Ugh, thanks for noticing this for me! That should now be resolved.

**Comment by kieranjmartin** [comment]
I believe this is no longer an issue, so closing this, please reopen if still the case @pixy61
